name: swissenergyforecast

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env.override
    container_name: swissenergyforecast-backend
    expose:
      - "8000"
    volumes:
      - swissenergyforecast-backend-data:/code/data
    networks:
      - swissenergyforecast-net 
      - nginx-proxy-manager-net # So that Nginx Proxy Manager can see these services

  frontend:
    build:
      context: .  
      dockerfile: frontend/Dockerfile
    container_name: swissenergyforecast-frontend
    networks:
      - swissenergyforecast-net
      - nginx-proxy-manager-net # So that Nginx Proxy Manager can see these services

volumes:
  swissenergyforecast-backend-data:
    name: swissenergyforecast-backend-data

networks:
  swissenergyforecast-net:
    driver: bridge
  nginx-proxy-manager-net:
    external: true