services:
  backend:
    networks:
      - npm-net # So that Nginx Proxy Manager can see these services

  frontend:
    networks:
      - npm-net # So that Nginx Proxy Manager can see these services

  scheduler:
    image: alpine:latest
    container_name: swissenergyforecast-scheduler
    depends_on:
      - backend
    networks:
      - swissenergyforecast-net
    command: >
      sh -c "apk add --no-cache curl &&
            echo '50 * * * * curl -s -X PUT http://backend:<BACKEND_PORT>/forecast/custom' | crontab - &&
            crond -f -l 2"
networks:
  npm-net:
    external: true
