services:
  backend:
    ports:
      - "8000:8000"
    command: [ "fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    env_file:
      - ./backend/.env.override
    develop:
      watch:
        - action: sync
          path: backend
          target: /src
          ignore:
            - "**/__pycache__/"
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: compose.yaml
        - action: rebuild
          path: compose.override.yaml
  frontend:
    ports:
      - "3000:80"
    develop:
      watch:
        - action: sync
          path: frontend
          target: /src
          ignore:
            - "**/__pycache__/"
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: compose.yaml
        - action: rebuild
          path: compose.override.yaml
