name: swissenergyforecast

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env.override
    container_name: swissenergyforecast-backend
    expose:
      - "8000"
    volumes:
      - swissenergyforecast-backend-data:/data
    networks:
      - swissenergyforecast-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: swissenergyforecast-frontend
    networks:
      - swissenergyforecast-net

volumes:
  swissenergyforecast-backend-data:
    name: swissenergyforecast-backend-data

networks:
  swissenergyforecast-net:
    driver: bridge
