services:
  backend:
    ports:
      - "8000:8000"
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - "**/__pycache__/"
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: compose.yaml
        - action: rebuild
          path: compose.override.yaml
  frontend:
    ports:
      - "3000:3000"