services:
  backend:
    restart: unless-stopped
    environment:
      - ENTSOE_API_KEY=${ENTSOE_API_KEY:?error}
    networks:
      - npm-net # So that Nginx Proxy Manager can see these services

  frontend:
    restart: unless-stopped
    networks:
      - npm-net # So that Nginx Proxy Manager can see these services

  scheduler:
    image: alpine:latest
    container_name: swissenergyforecast-scheduler
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - swissenergyforecast-net
    command: >
      sh -c "apk add --no-cache curl &&
        echo '50 * * * * curl -s -X PUT http://swissenergyforecast-backend:8000/forecast/custom' | crontab - &&
        crond -f -l 2"
networks:
  npm-net:
    external: true
