name: swissenergyforecast

services:
  backend:
    container_name: swissenergyforecast-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ./backend/.env.override
    volumes:
      - swissenergyforecast-backend-data:/src/data
    networks:
      - swissenergyforecast-net

  frontend:
    container_name: swissenergyforecast-frontend
    depends_on:
      - backend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - swissenergyforecast-net

volumes:
  swissenergyforecast-backend-data:
    name: swissenergyforecast-backend-data

networks:
  swissenergyforecast-net:
    driver: bridge
