services:
  backend:
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./uv.lock